### ISSUE TITLE
Java language support

### ISSUE THREAD

**Issue by JonathanDavies626** [camel-tooling/vscode-camelk#1591]
Java language support doesn't seem to work. imports cannot be resolved:

![Java Language Support](https://github.com/camel-tooling/vscode-camelk/assets/13573974/da25cb71-2065-431a-baba-0962091eb579)

An uncaught error is reported in the runtime status for the extension "the argument stdio is invalid" (not sure if this is relevant).

![Extension](https://github.com/camel-tooling/vscode-camelk/assets/13573974/c451c8ac-42ae-4b68-b087-ddbee3864e42)

Please help, I don't know how to begin to diagnose this issue!

**Comment by apupier** [comment]
Hi,

the first things to check are listed here https://github.com/camel-tooling/vscode-camelk/wiki/Trouble-Shooting-Java-compilation-errors-in-Camel-K-integration-java-files

Please let us know if it helps

**Comment by JonathanDavies626** [comment]
Thanks, I didn't notice the Wiki. This was helpful although I still have some problems.

There is no .project or .classpath files.

The file .vscode/settings.json looks okay:

```
{
    "java.project.referencedLibraries": [
        "lib/**/*.jar",
        "c:\\Users\\jo166518\\AppData\\Roaming\\Code\\User\\globalStorage\\redhat.vscode-camelk\\java-dependencies-3.20.1\\dependencies/*.jar"
    ]
}

```

The directory '%USERPOFILE%\AppData\Roaming\Code\User\globalStorage\redhat.vscode-camelk\java-dependencies-3.20.1' exists on my machine but is empty.

Language support for Apache Camel log:
```
Aug 25, 2023 2:43:25 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 1
Aug 25, 2023 2:43:34 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 4
Aug 25, 2023 2:43:34 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 3
Aug 25, 2023 2:43:36 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleNotification
WARNING: Notification threw an exception: {
  "jsonrpc": "2.0",
  "method": "$/setTrace",
  "params": {
    "value": "off"
  }
}
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$recursiveFindRpcMethods$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$recursiveFindRpcMethods$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.UnsupportedOperationException
	at org.eclipse.lsp4j.services.LanguageServer.setTrace(LanguageServer.java:125)
	... 16 more

Aug 25, 2023 2:44:06 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 8
```

Language Support for Java log:

```
[Error - 2:44:16 PM] 25 Aug 2023, 14:44:16 Error occured while building workspace. Details: 
 message: The import org.apache cannot be resolved; code: 268435846; resource: C:/Users/jo166518/source/Demo/HelloWorld.java; line: 3
 message: RouteBuilder cannot be resolved to a type; code: 16777218; resource: C:/Users/jo166518/source/Demo/HelloWorld.java; line: 5
 message: The method configure() of type HelloWorld must override or implement a supertype method; code: 67109498; resource: C:/Users/jo166518/source/Demo/HelloWorld.java; line: 7
 message: The method from(String) is undefined for the type HelloWorld; code: 67108964; resource: C:/Users/jo166518/source/Demo/HelloWorld.java; line: 10
 ```

Log for Apache Camel K

```
Found Kubernetes CLI (kubectl) version 1.25... 
Error: cannot read sources: failed to resolve sources: missing file or unsupported scheme in /C:/Users/jo166518/source/Demo/HelloWorld.java
Error while trying to refresh Java classpath based on file /C:/Users/jo166518/source/Demo/HelloWorld.java:
1
Error: cannot read sources: failed to resolve sources: missing file or unsupported scheme in /C:/Users/jo166518/source/Demo/HelloWorld.java
```

I can successfully run the kamel local build command in the terminal, which results in dependencies being copied to the integration directory. This fixes the issue*:

```
kamel local build --integration-directory "c:\Users\jo166518\AppData\Roaming\Code\User\globalStorage\redhat.vscode-camelk\java-dependencies-3.20.1" ".\source\Demo\HelloWorld.java"
```

*clicking on 'Refresh classpath dependencies' causes the directory to be emptied again.

**Comment by apupier** [comment]
latest snapshot here contains the fix https://download.jboss.org/jbosstools/vscode/snapshots/vscode-camelk/

I plan to do a release this afternoon (to have it directly on the marketplace)

Thank you for having reported the issue.
