### ISSUE TITLE
Fixing Cannot read property 'catch' of undefined issue

### ISSUE THREAD

**Issue by bfitzpat** [camel-tooling/vscode-camelk#171]
This issue has cropped up on Travis-ci

```rejected promise not handled within 1 second: TypeError: Cannot read property 'catch' of undefined

stack trace: TypeError: Cannot read property 'catch' of undefined

	at CamelKNodeProvider.<anonymous> (/home/travis/build/camel-tooling/vscode-camelk/out/CamelKNodeProvider.js:60:41)

	at Generator.next (<anonymous>)

	at /home/travis/build/camel-tooling/vscode-camelk/out/CamelKNodeProvider.js:8:71

	at new Promise (<anonymous>)

	at __awaiter (/home/travis/build/camel-tooling/vscode-camelk/out/CamelKNodeProvider.js:4:12)

	at Promise (/home/travis/build/camel-tooling/vscode-camelk/out/CamelKNodeProvider.js:56:49)

	at new Promise (<anonymous>)

	at CamelKNodeProvider.addChild (/home/travis/build/camel-tooling/vscode-camelk/out/CamelKNodeProvider.js:56:16)

	at integrationExplorer.getChildren.then (/home/travis/build/camel-tooling/vscode-camelk/out/test/suite/integrationExplorer.test.js:42:33)

rejected promise not handled within 1 second: TypeError: Cannot read property 'catch' of undefined

stack trace: TypeError: Cannot read property 'catch' of undefined

	at CamelKNodeProvider.<anonymous> (/home/travis/build/camel-tooling/vscode-camelk/out/CamelKNodeProvider.js:60:41)

	at Generator.next (<anonymous>)

	at /home/travis/build/camel-tooling/vscode-camelk/out/CamelKNodeProvider.js:8:71

	at new Promise (<anonymous>)

	at __awaiter (/home/travis/build/camel-tooling/vscode-camelk/out/CamelKNodeProvider.js:4:12)

	at Promise (/home/travis/build/camel-tooling/vscode-camelk/out/CamelKNodeProvider.js:56:49)

	at new Promise (<anonymous>)

	at CamelKNodeProvider.addChild (/home/travis/build/camel-tooling/vscode-camelk/out/CamelKNodeProvider.js:56:16)

	at integrationExplorer.getChildren.then (/home/travis/build/camel-tooling/vscode-camelk/out/test/suite/integrationExplorer.test.js:54:33)

rejected promise not handled within 1 second: TypeError: Cannot read property 'catch' of undefined

stack trace: TypeError: Cannot read property 'catch' of undefined

	at CamelKNodeProvider.<anonymous> (/home/travis/build/camel-tooling/vscode-camelk/out/CamelKNodeProvider.js:75:45)

	at Generator.next (<anonymous>)

	at /home/travis/build/camel-tooling/vscode-camelk/out/CamelKNodeProvider.js:8:71

	at new Promise (<anonymous>)

	at __awaiter (/home/travis/build/camel-tooling/vscode-camelk/out/CamelKNodeProvider.js:4:12)

	at Promise (/home/travis/build/camel-tooling/vscode-camelk/out/CamelKNodeProvider.js:69:49)

	at new Promise (<anonymous>)

	at CamelKNodeProvider.removeChild (/home/travis/build/camel-tooling/vscode-camelk/out/CamelKNodeProvider.js:69:16)

	at integrationExplorer.getChildren.then (/home/travis/build/camel-tooling/vscode-camelk/out/test/suite/integrationExplorer.test.js:55:33)

```

**Comment by djelinek** [comment]
verified with master branch
