### ISSUE TITLE
Track down "channel has been closed" error

### ISSUE THREAD

**Issue by bfitzpat** [camel-tooling/vscode-camelk#87]
Seeing this in the debug console sometimes... 
```
rejected promise not handled within 1 second: Error: Channel has been closed
extensionHostProcess.js:775
stack trace: Error: Channel has been closed
	at l.validate (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:582:372)
	at l.append (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:581:920)
	at l.append (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:675:780)
	at define.createOutputChannel.append.t.then.t (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:583:531)
```

**Comment by bfitzpat** [comment]
https://github.com/camel-tooling/vscode-camelk/pull/89

**Comment by djelinek** [comment]
verified - Tooling for Apache Camel K by Red Hat (marketplace version 0.0.9)
